
<div style="margin:10px auto; padding-top:10px clear:both">
	<div style="float:left;  color:#000000;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px;">
	<a href="#" target="_parent">Privacy Policy</a> | <a href="#" target="_parent">Terms & Conditions</a> | <a href="#" target="_parent">How to Partner with HPC</a> | <a href="#" target="_parent">Disclaime</a>r | <a href="#" target="_parent">Sitemap </a><br />

      Powered by :- <a href="http://www.focus-itech.com">www.focus-itech.com</a><br>
	  Best viewed in 1024 x 768 on Mozilla Firefox
	</div>
	<div style="float:right;">
		<a href="/"><img src="images/logo-down.gif" alt="logo himachal pradesh" width="254" height="58" border="0" /> </a>
	</div>
</div>
